### ISSUE TITLE
Factor in the weigthed reward sum is inconsistent with the paper

### ISSUE THREAD

**Issue by NohTow** [j-min/CLIP-Caption-Reward#11]
Hello,

In the paper, the "reward augmented with the grammar score" is defined as:
$$R(I,c) = CLIP-S(i,c) + \lambda g(c)$$ with $\lambda=2.0$.
However, in the code,[ this is the clip_s reward that is multiplied by the 2.0 scalar](https://github.com/j-min/CLIP-Caption-Reward/blob/ca5fe53b848d7e7b1fb9808984f7a3187b2a32d6/captioning/utils/rewards.py#L312) (in addition to the 2.5 factor from the definition of CLIP_S): `rewards = opt.clipscore_reward_weight * rewards`

The two rewards are[ then directly summed](https://github.com/j-min/CLIP-Caption-Reward/blob/ca5fe53b848d7e7b1fb9808984f7a3187b2a32d6/captioning/modules/loss_wrapper.py#L92) and I can't find the grammar reward being scaled anywhere (especially not by 4.0, to balance the 2.0 factor of the clipscore reward), so I think there has been an inversion somewhere.

Since I am reproducing results with my own code, it would be really helpful to know which scaling is the correct one, because one constraint the language model more than the other.

**Comment by j-min** [comment]
Hi Antoine, thanks for pointing it out. I found that I swapped the lambdas in my implementation.

The reward function was calculated as
`Reward(image, caption) = CLIPScore(image, caption) * 2.0 + grammar_score(caption)`
instead of 
`Reward(image, caption) = CLIPScore(image, caption) + grammar_score(caption) * 2.0`.

I used `Reward(image, caption) = CLIPScore(image, caption) * 2.0 + grammar_score(caption)` in my experiments, as in the current repo.
You don't need to edit the code, and I'll update the equation in Arxiv soon.

**Comment by NohTow** [comment]
Thanks for your quick answer. This make sense, because when using the equation from the paper, my model was not learning, whereas with the definition of the repo, it is working fine.

Please note that, in this case, the $\lambda$ can be merged with the weight in the CLIP_S. I think merging the two in a factor of 5 helps better visualize the scale between weight of the similarity of the caption with the image and the grammar score.

I understand that it is done to stay consistent with the original definition of CLIP_Score (as for the ReLU, which is doing nothing in practice since the similarities of generated caption are always >0), so I understand if you want to keep both scalar separated. Maybe you can add a quick sentence mentioning that both terms act together to scale the weight of the similarity compared to the grammar to convey the idea without merging the two factors.

In any case, thanks for you quick answer and congratulations on your fine work !
