### ISSUE TITLE
difference between clip_prepo_feat.py and clipscore_prepo_feat.py

### ISSUE THREAD

**Issue by nikky4D** [j-min/CLIP-Caption-Reward#2]
What is the difference between clip_prepo_feat.py and clipscore_prepo_feat.py? Why do we need to run both for visual feature extraction?

**Comment by j-min** [comment]
I used a captioning model that uses CLIP-RN50 features as visual input. `clip_prepo_feat.py` is a script for extracting these.

For the reward model, I used CLIP-ViT/B32. `clipscore_prepo_feat.py` is a script for extracting visual features to calculate rewards.

You can try using the same or different CLIP visual features for captioning model and reward model for your purposes.

**Comment by nikky4D** [comment]
Thanks for the update.
