### ISSUE TITLE
Where is the file 'data/ finecapeval. json'?

### ISSUE THREAD

**Issue by hhy12336** [j-min/CLIP-Caption-Reward#3]
Hi,

Thank you for this amazing contribution!
I can't find the 'data/ finecapeval. json' file.Could you give me some guidance?

**Comment by j-min** [comment]
Hi, I just uploaded the FineCapEval.json data to [google drive](https://drive.google.com/drive/folders/1jlwInAsVo-PdBdJlmHKPp34dLnxIIMLx?usp=sharing).
