### ISSUE TITLE
phase 2 of clips

### ISSUE THREAD

**Issue by 232525** [j-min/CLIP-Caption-Reward#9]
Sorry for bothering again! A question about the model saving strategy in clips (similar to clips + grammar) training.
I notice the code always saves the highest cider score model as the best model during the training.

But, most metrics are decreasing except CLIP-S during the training process under clips RL. How do you choose the "best" model? By choosing the highest CLIP-S score? If true, under other RL (such as CIDEr and CIDEr + CLIPS), should adopt the same way (instead of the highest CIDEr score model) to choose the "best" model?
![image](https://user-images.githubusercontent.com/20409609/188312396-3f028aa7-ea4a-4b9b-a3ee-e41d75fd0700.png)

**Comment by j-min** [comment]
Hi, I just chose the checkpoint with the last epoch (total of 40), without considering val/CIDEr. Of course, for your purpose, you can choose a checkpoint with the highest validation metric of your interest.

**Comment by 232525** [comment]
Thanks for your reply!
